### DISCUSSION TITLE
Sensor list doesnt seem to work after upgrade

### DISCUSSION THREAD

**Discussion by ozhound** [cytech/Home-Assistant-wundergroundpws#142] [General]
Sensors not loading after upgrade to HA to 2023.1 and then upgrading to This plugin to 1.1.0

Upgraded via HACS. Didnt stop HA, but rebooted device after the upgrade.

the Weather card works fine and pulls current conditions via my wunderground API as per before the upgrade, but all of the entites i configured have disconnected. Tried Deleting them, restarting and still no entities.

**Comment by cytech** [comment]
upgraded via HACS?
did the "translations" directory get created and populated under the "custom_components/wundergroundpws" directory?

**Comment by rudizl** [comment]
> Sensors not loading after upgrade to HA to 2023.1 and then upgrading to This plugin to 1.1.0
> 
> Upgraded via HACS. Didnt stop HA, but rebooted device after the upgrade.
> 
> the Weather card works fine and pulls current conditions via my wunderground API as per before the upgrade, but all of the entites i configured have disconnected. Tried Deleting them, restarting and still no entities.

Update via HACS works perfect, but have you rewrite your configuration.yaml according to the new format:

```
# Example configuration.yaml entry
# REQUIRED
wundergroundpws:
  api_key: YOUR_API_KEY
  pws_id: YOUR_STATION_ID
  numeric_precision: none

# Required to generate HASS weather Entity for weather forecast card
weather:
  - platform: wundergroundpws

# Required if you wish to add sensors
sensor:
  - platform: wundergroundpws
    monitored_conditions:
      - temp
      - dewpt
      - heatIndex
   ```
