### DISCUSSION TITLE
Convert sensors to native weather entity

### DISCUSSION THREAD

**Discussion by totti4ever** [cytech/Home-Assistant-wundergroundpws#95] [Show and tell]
In order to use the plain vanilla lovelace cards youhave to provide them a weather entitity. Sadly this integration comes without and as #2 is already waiting for a long time I started templating such an entity. This worked quite well and I want to share my outcome:

_sensor (nothing new)_
```
sensor:

  - platform: wundergroundpws
    api_key: $$$ YOUR API KEY $$$
    pws_id: $$$ YOUR ID $$$
    numeric_precision: none
    monitored_conditions:
      - solarRadiation
      - uv
      - winddir
      - humidity
      - dewpt
      - heatIndex
      - windChill
      - precipTotal
      - precipRate
      - pressure
      - temp
      - windGust
      - windSpeed
      - weather_1d
      - weather_1n

      - temp_high_1d
      - temp_low_1d
      - precip_1d
      - precip_chance_1d
      - wind_1d

      - temp_high_2d
      - temp_low_2d
      - precip_2d
      - precip_chance_2d
      - wind_2d

      - temp_high_3d
      - temp_low_3d
      - precip_3d
      - precip_chance_3d
      - wind_3d

      - temp_high_4d
      - temp_low_4d
      - precip_4d
      - precip_chance_4d
      - wind_4d

      - temp_high_5d
      - temp_low_5d
      - precip_5d
      - precip_chance_5d
      - wind_5d

    lang: de-DE
```

template:
```
weather:
  - platform: template
    name: WUnderground Template
    temperature_template: "{{ states('sensor.wupws_temp') | float }}"
    humidity_template: "{{ states('sensor.wupws_humidity') | float }}"
    pressure_template: "{{ states('sensor.wupws_pressure') | int }}"
    wind_speed_template: "{{ states('sensor.wupws_windspeed') | float }}"
    wind_bearing_template: "{{ states('sensor.wupws_winddir') | float }}"
    attribution_template: "{{ state_attr('sensor.wupws_temp', 'attribution') }}"

    condition_template: >

      {% set condition_id = state_attr('sensor.wupws_weather_1d', 'entity_picture') | regex_replace(find='/local/wupws_icons/', replace='', ignorecase=False) | regex_replace(find='.png', replace='', ignorecase=False) | int(0) %}

      {% if condition_id in [31] -%}
        clear-night
      {% elif condition_id in [26,27,28] -%}
        cloudy
      {% elif condition_id in [19,21,22] -%}
        exceptional
      {% elif condition_id in [20] -%}
        fog
      {% elif condition_id in [17,25,35] -%}
        hail
      {% elif condition_id in [47] -%}
        lightning
      {% elif condition_id in [26,27,28] -%}
        cloudy
      {% elif condition_id in [37,38] -%}
        lightning-rainy
      {% elif condition_id in [4] -%}
        Lightning/ thunderstorms and rain
      {% elif condition_id in [29,30] -%}
        partlycloudy
      {% elif condition_id in [9,11,12,39,45] -%}
        rainy
      {% elif condition_id in [5,13,14,15,16,41,42,43,46] -%}
        snowy
      {% elif condition_id in [6,7,8,10,18] -%}
        snowy-rainy
      {% elif condition_id in [32,33,34,36] -%}
        sunny
      {% elif condition_id in [0,1,2,3,23,24,40] -%}
        windy
      {% elif condition_id in [44] -%}
        Not Available (N/A)
      {%- else -%}
        unknown
      {%- endif %}


    # forecast_template: "{{ state_attr('weather.dwd_weather_muenster_zentrum', 'forecast') }}"
    forecast_template: >-
      [
        {
          {% set dat = now() + timedelta( days = 0 ) %}
          "datetime": "{{ dat.strftime("%Y-%m-%dT00:00:00Z") }}",
          "temperature": {{ states('sensor.wupws_temp_high_1d') }},
          "templow": {{ states('sensor.wupws_temp_low_1d') }},
          "precipitation": {{ states('sensor.wupws_precip_1d') }},
          "precipitation_probability": {{ states('sensor.wupws_precip_chance_1d') }},
          "wind_speed": {{ states('sensor.wupws_wind_1d') }},
          
        },
        {
          {% set dat = now() + timedelta( days = 1 ) %}
          "datetime": "{{ dat.strftime("%Y-%m-%dT00:00:00Z") }}",
          "temperature": {{ states('sensor.wupws_temp_high_2d') }},
          "templow": {{ states('sensor.wupws_temp_low_2d') }},
          "precipitation": {{ states('sensor.wupws_precip_2d') }},
          "precipitation_probability": {{ states('sensor.wupws_precip_chance_2d') }},
          "wind_speed": {{ states('sensor.wupws_wind_2d') }},
        },
        {
          {% set dat = now() + timedelta( days = 2 ) %}
          "datetime": "{{ dat.strftime("%Y-%m-%dT00:00:00Z") }}",
          "temperature": {{ states('sensor.wupws_temp_high_3d') }},
          "templow": {{ states('sensor.wupws_temp_low_3d') }},
          "precipitation": {{ states('sensor.wupws_precip_3d') }},
          "precipitation_probability": {{ states('sensor.wupws_precip_chance_3d') }},
          "wind_speed": {{ states('sensor.wupws_wind_3d') }},
        },
        {
          {% set dat = now() + timedelta( days = 3 ) %}
          "datetime": "{{ dat.strftime("%Y-%m-%dT00:00:00Z") }}",
          "temperature": {{ states('sensor.wupws_temp_high_4d') }},
          "templow": {{ states('sensor.wupws_temp_low_4d') }},
          "precipitation": {{ states('sensor.wupws_precip_4d') }},
          "precipitation_probability": {{ states('sensor.wupws_precip_chance_4d') }},
          "wind_speed": {{ states('sensor.wupws_wind_4d') }},
        },
        {
          {% set dat = now() + timedelta( days = 4 ) %}
          "datetime": "{{ dat.strftime("%Y-%m-%dT00:00:00Z") }}",
          "temperature": {{ states('sensor.wupws_temp_high_5d') }},
          "templow": {{ states('sensor.wupws_temp_low_5d') }},
          "precipitation": {{ states('sensor.wupws_precip_5d') }},
          "precipitation_probability": {{ states('sensor.wupws_precip_chance_5d') }},
          "wind_speed": {{ states('sensor.wupws_wind_5d') }},
        }
      ]
```

What is still missing?
The mapping of the conditions for the forecast. This would work the same way as for the current conditions, just that you have to repeat it 5 times. Maybe I'll dive into python to outsource this to a small function which can then be called at all places...let's see!

What is working?
<img width="382" alt="grafik" src="https://user-images.githubusercontent.com/49901208/159912145-ae357c72-1000-4049-bba1-fa831fb397c4.png">
