### ISSUE TITLE
Error Configuration.yaml not in default directory

### ISSUE THREAD

**Issue by e1nzelkind** [cytech/Home-Assistant-wundergroundpws#1]
Hey cytech!

Thanks for creating the component! That I'm searching for!!! 

But i got an error, when I activate the sensor in my configuration...

In my configuration.yaml, i configured this:

**sensor: !include sensors.yaml**

when i fill the sensors.yaml with the sensor variables and use the config checker, then i got a lot of errors like this:

> Error handling request
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/config.py", line 336, in load_yaml_config_file
    conf_dict = load_yaml(config_path)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/util/yaml.py", line 92, in load_yaml
    with open(fname, encoding='utf-8') as conf_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/homeassistant/.homeassistant/configuration.yaml'

During handling of the above exception, another exception occurred:
> 

The error like this is confusing me:

> FileNotFoundError: [Errno 2] No such file or directory: '/home/homeassistant/.homeassistant/configuration.yaml'

> 

because my configuration.yaml is here:
/home/homeassistant/configuration.yaml

Can you help me? 

Best regards from Germany!
Dennis

**Comment by cytech** [comment]
not sure, check your sensors.yaml syntax
should look something like this:
```
- platform: wundergroundpws
  api_key: !secret wunderground_api_key
  pws_id: YOURSTATIONID
  monitored_conditions:
    - humidity
    - temp
    - dewpt
    - heatIndex
    - windChill
    - precipRate
    - precipTotal
    - pressure
    - windGust
    - windSpeed
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_2n
    - weather_3d
    - weather_3n
    - weather_4d
    - weather_4n
    - weather_5d
    - weather_5n
    - temp_high_1d
    - temp_low_1d
    - wind_1d
    - precip_1d
    - precip_chance_1d
    - winddir
    - neighborhood
    - obsTimeLocal
    - stationID
    - elev
    - today_summary
```
