### ISSUE TITLE
Integration could not be set up after updating to branch 1.X.X

### ISSUE THREAD

**Issue by AdmiralStipe** [cytech/Home-Assistant-wundergroundpws#119]
IF YOU ARE NOT REPORTING A REPRODUCIBLE BUG, PLEASE USE DISCUSSIONS
**Describe the bug**
After updating to branch 1.0.0 and also to 1.0.1 and following the update instructions (almost) to the letter, the integration just stopped working and can not be set up at HA start. Previous version worked without problems. 

**To Reproduce**
1. Update to 1.X.X'
2. Change configuration.yaml as instructed
3. Restart

**Screenshots**
![errors](https://user-images.githubusercontent.com/64564398/205341055-9aa97f4f-f501-4762-a6f4-2dc5314401c0.png)

**Desktop (please complete the following information):**
 - OS: HA Supervised (Debian 11)
 - Version: HA core-2022.11.5, supervisor-2022.11.2

**Additional context**
My configuration:

**configuration.yaml**

```
wundergroundpws:
  api_key: !secret wuapi_key
  pws_id: IIDRIJ44
  numeric_precision: decimal
  lang: sl-SI
weather:
  - platform: wundergroundpws   
sensor: !include sensor.yaml
```

**sensor.yaml**

```
- platform: wundergroundpws
  monitored_conditions:
    - humidity
    - temp
    - dewpt
    - heatIndex
    - windChill
    - precipRate
    - precipTotal
    - pressure
    - windGust
    - windSpeed
    - winddir
    - obsTimeLocal
```

**secrets.yaml**

```
wuapi_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
survusername: XXXXXXXXX
survpassword: XXXXXXXXXXXX
authuser: XXXXXXXXX
authpass: XXXXXXXXXXXX
wifi_ssid: XXXXXXXX
wifi_password: XXXXXXXXXXXX
```
