### ISSUE TITLE
Platform wundergroundpws does not generate unique IDs. ID XXXXX already exists - ignoring weather.xxxxx

### ISSUE THREAD

**Issue by Asom-Velz** [cytech/Home-Assistant-wundergroundpws#148]
Hi

After the update from 0.8 to 1.1 
I receive the following error and I can;t figure out what is wrong
"Platform wundergroundpws does not generate unique IDs. ID INA already exists - ignoring weather.ina"

I have the weather card (attached picture Clipboard-1) but all the sensors are unavailable (attached picture Clipboard-2)

This is the modified yaml for v1.1:

```
#WU_PWS entries | Changed for v1.1.0 |20Jan23
wundergroundpws:
  api_key: !secret wu_apikey
  pws_id: !secret wu_pwsid
  numeric_precision: none
#Required to generate HASS weather Entity for weather forecast card
weather:
  - platform: wundergroundpws
#Required if you wish to add sensors
  - platform: wundergroundpws
    sensors:
    monitored_conditions:
      - dewpt
      - elev
      - heatIndex
      - humidity
      - neighborhood
      - obsTimeLocal
      - precip_1d
      - precip_2d
      - precip_3d
      - precip_4d
      - precip_5d
      - precip_chance_1d
      - precip_chance_1n
      - precip_chance_2d
      - precip_chance_2n
      - precip_chance_3d
      - precip_chance_3n
      - precip_chance_4d
      - precip_chance_4n
      - precip_chance_5d
      - precip_chance_5n
      - precipRate
      - precipTotal
      - pressure
      - solarRadiation
      - stationID
      - temp
      - temp_high_1d
      - temp_high_2d
      - temp_high_3d
      - temp_high_4d
      - temp_high_5d
      - temp_low_1d
      - temp_low_2d
      - temp_low_3d
      - temp_low_4d
      - temp_low_5d
      - today_summary
      - uv
      - weather_1d
      - weather_1n
      - weather_2d
      - weather_2n
      - weather_3d
      - weather_3n
      - weather_4d
      - weather_4n
      - weather_5d
      - weather_5n
      - wind_1d
      - wind_2d
      - wind_3d
      - wind_4d
      - wind_5d
      - windChill
      - winddir
      - windDirectionName
      - windGust
      - windSpeed
```
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 Enterprise 22H2 19045.2486
 - Browser Firefox
 - Version 109   
 - 
![Clipboard-1](https://user-images.githubusercontent.com/65943619/213906839-8e51a1bb-c117-48e7-bb91-36ac7478895c.jpg)
![Clipboard-2](https://user-images.githubusercontent.com/65943619/213906841-c203cf0e-f788-45e3-b734-ca39b68e3410.jpg)

**Comment by rudizl** [comment]
Is this all in your configuration.yaml, or you use split configuration like `sensor: !include sensors.yaml
`?

**Comment by Asom-Velz** [comment]
No this is only the part for wupws configuration. Nothing else in the configuration.yaml state something for wupws config

**Comment by rudizl** [comment]
Than the thing should look like this:
````
#WU_PWS entries | Changed for v1.1.0 |20Jan23
wundergroundpws:
     api_key: !secret wu_apikey
     pws_id: !secret wu_pwsid
     numeric_precision: none
weather:
     - platform: wundergroundpws
sensors:
    - platform: wundergroundpws
      monitored_conditions:
           - dewpt
           - elev
           - heatIndex
           - humidity
     
  ````

**Comment by Asom-Velz** [comment]
When I made it as you propose I receive the error 
Integration error: sensors - Integration 'sensors' not found.

````
#WU_PWS` entries | Changed for v1.1.0 |20Jan23
wundergroundpws:
  api_key: !secret wu_apikey
  pws_id: !secret wu_pwsid
  numeric_precision: none

#Required to generate HASS weather Entity for weather forecast card
weather:
  - platform: wundergroundpws

#Required if you wish to add sensors
sensors:
  - platform: wundergroundpws
    monitored_conditions:
      - dewpt
      - elev
      - heatIndex
      - humidity
      - neighborhood
      - obsTimeLocal
      - precip_1d
      - precip_2d
      - precip_3d
     ````
