### ISSUE TITLE
Current condition in HA differs from condition on wunderground website

### ISSUE THREAD

**Issue by AndLindemann** [cytech/Home-Assistant-wundergroundpws#176]
**Describe the bug**
Home assistant current condition is not the same as the current condition reported on the wunderground site for the station.
Currently the home assistant weather entity current condition is "rainy", whereas if I check the wunderground website for my station id, it is "partly cloudy". See screenshots.

**To Reproduce**
1. Check Home Assistant weather entity. Current condition at the moment is "rainy".
2. Go to wunderground website for the same station id. Current condition there is "partly cloudy".

**Expected behavior**
I'd think current condition in HA should be the same as on wunderground. 
It looks like instead it uses the condition from todays forecast entity as the current condition in HA instead, as the forecast[0] entry actually says "rainy" as it might rain later today. See the entity data from HA below. 

**Screenshots**
<img width="879" alt="image" src="https://github.com/cytech/Home-Assistant-wundergroundpws/assets/4157845/96394b7b-5521-4534-96db-4366d8670e46">

https://www.wunderground.com/weather/de/gladbeck/IGLADB59
<img width="713" alt="image" src="https://github.com/cytech/Home-Assistant-wundergroundpws/assets/4157845/daa3b634-623e-47f0-af29-6e1580a119cf">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version 16.5.1

**Additional context:**

weather entity from igladb59 station:
<img width="879" alt="image" src="https://github.com/cytech/Home-Assistant-wundergroundpws/assets/4157845/94ac9e9e-3259-48e0-a09e-d97cfb089527">

```
temperature: 17.8
temperature_unit: °C
humidity: 91
pressure: 1021.3
pressure_unit: hPa
wind_bearing: 231
wind_speed: 9.7
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
forecast:
  - condition: rainy
    precipitation: 0
    precipitation_probability: 30
    temperature: 26
    templow: 16
    datetime: 1687496400000
    wind_bearing: NW
    wind_speed: 15
  - condition: sunny
    precipitation: 0
    precipitation_probability: 5
    temperature: 28
    templow: 17
    datetime: 1687582800000
    wind_bearing: WSW
    wind_speed: 10
  - condition: sunny
    precipitation: 0
    precipitation_probability: 4
    temperature: 31
    templow: 20
    datetime: 1687669200000
    wind_bearing: SSO
    wind_speed: 7
  - condition: rainy
    precipitation: 1.1
    precipitation_probability: 39
    temperature: 23
    templow: 15
    datetime: 1687755600000
    wind_bearing: W
    wind_speed: 22
  - condition: cloudy
    precipitation: 0
    precipitation_probability: 10
    temperature: 23
    templow: 16
    datetime: 1687842000000
    wind_bearing: WSW
    wind_speed: 16
friendly_name: IGLADB59

```
