### ISSUE TITLE
Integration in dashboard of home assistant

### ISSUE THREAD

**Issue by Joezi79** [cytech/Home-Assistant-wundergroundpws#35]
Hello, I have integrated my weather station by using this integration. Now, I would like to display all the values of the wunderground wps. Unfortunately, I am missing some examples of how to configure the dashboard of home assistant. Is there anyone who can send me an example of how to integrate sensors in dashboard. I would like to have a good looking dashboard with all values ...

**Comment by TheNogl** [comment]
Here is my dashboard, it is in German, but I think you can make out what most of it means:
![grafik](https://user-images.githubusercontent.com/19914064/93630238-f2894500-f9e9-11ea-9639-17fc3fb5b8b9.png)

The "Windrichtung"(wind direction) sensor is a custom template sensor, which I found here: [https://community.home-assistant.io/t/sensor-wind-compass-up-for-grabs/52425](https://community.home-assistant.io/t/sensor-wind-compass-up-for-grabs/52425
)

The code:
```
cards:
  - cards:
      - entity: sensor.wupws_temp
        max: 50
        min: -30
        severity:
          green: 5
          red: 35
          yellow: 30
        type: gauge
      - entity: sensor.wupws_humidity
        max: 100
        min: 0
        type: gauge
      - entity: sensor.wupws_pressure
        max: 1063.25
        min: 963.25
        type: gauge
    type: horizontal-stack
  - cards:
      - entity: sensor.wupws_preciptotal
        max: 50
        min: 0
        type: gauge
      - entity: sensor.wupws_solarradiation
        max: 1000
        min: 0
        type: gauge
      - entity: sensor.wupws_uv
        max: 12
        min: 0
        severity:
          green: 0
          red: 8
          yellow: 4
        type: gauge
    type: horizontal-stack
  - cards:
      - entity: sensor.wupws_windspeed
        max: 100
        min: 0
        severity:
          green: 0
          red: 80
          yellow: 30
        type: gauge
      - entity: sensor.wind_compass
        show_entity_picture: true
        size: 90px
        type: 'custom:button-card'
      - entity: sensor.wupws_windgust
        max: 100
        min: 0
        severity:
          green: 0
          red: 80
          yellow: 30
        type: gauge
    type: horizontal-stack
type: vertical-stack
```
