### ISSUE TITLE
Sample configuration.yaml errors for group

### ISSUE THREAD

**Issue by bjs-pdx** [cytech/Home-Assistant-wundergroundpws#38]
In the sample configuration.yaml you have the following entries for group:

```
 group:
      daily_forecast:
        name: Daily Forecast
        entities:
          - sensor.pws_weather_1d
          - sensor.pws_weather_1n
          - sensor.pws_weather_2d
          - sensor.pws_weather_2n
          - sensor.pws_weather_3d
          - sensor.pws_weather_3n
          - sensor.pws_weather_4d
          - sensor.pws_weather_4n
```
The entries should be sensor.wupws_*

**Comment by bjs-pdx** [comment]
Using the correct syntax for the sensor group, I still get a status of unknown for the group.

Entries in group.yaml (using include statement in configuration.yaml):
```
daily_forecast:
  name: Daily Forecast
  entities:
    - sensor.wupws_weather_1d
    - sensor.wupws_weather_1n
    - sensor.wupws_weather_2d
    - sensor.wupws_weather_2n
    - sensor.wupws_weather_3d
    - sensor.wupws_weather_3n
    - sensor.wupws_weather_4d
    - sensor.wupws_weather_4n
    - sensor.wupws_weather_5d
    - sensor.wupws_weather_5n
weather_current:
  name:  Current Weather
  entities:
    - sensor.wupws_obsTimeLocal
    - sensor.wupws_stationID
    - sensor.wupws_temp
    - sensor.wupws_dewpt
    - sensor.wupws_precipRate
    - sensor.wupws_precipTotal
    - sensor.wupws_windGust
    - sensor.wupws_WindSpeed
    - sensor.wupws_winddir
```
Using an entities card I can display each of the sensors correctly.
