### ISSUE TITLE
Freeze HA installing the integration

### ISSUE THREAD

**Issue by giorgiomanieri** [cytech/Home-Assistant-wundergroundpws#43]
Hi,
I've tried installing the integration following the instructions (custom_component folder and configuration.yaml settings), but after saved the configuration and restart the server, all the sensor are disabled (I use Xiaomi sensors for other purposes) and the configuration checker doesn't work.

```
sensor:
  - platform: wundergroundpws
    api_key: *CENSORED*
    pws_id: *CENSORED*
    monitored_conditions:
    - humidity
    - temp
    - dewpt
    - heatIndex
    - windChill
    - precipRate
    - precipTotal
    - pressure
    - windGust
    - windSpeed
    - temp_high_1d
    - temp_low_1d
    - wind_1d
    - precip_1d
    - precip_chance_1d
    - winddir
    - neighborhood
    - obsTimeLocal
    - stationID
    - elev
    - today_summary
```
Error log:

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
>     resp = await self._request_handler(request)
>   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
>     resp = await handler(request)
>   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
>     result = await result
>   File "/usr/src/homeassistant/homeassistant/components/config/core.py", line 29, in post
>     errors = await async_check_ha_config_file(request.app["hass"])
>   File "/usr/src/homeassistant/homeassistant/config.py", line 874, in async_check_ha_config_file
>     res = await check_config.async_check_ha_config_file(hass)
>   File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 202, in async_check_ha_config_file
>     platform = p_integration.get_platform(domain)
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 424, in get_platform
>     cache[full_name] = self._import_platform(platform_name)
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 429, in _import_platform
>     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
>   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/config/custom_components/wundergroundpws/sensor.py", line 45, in <module>
>     load_config = config.load_yaml_config_file('/home/homeassistant/configuration.yaml')
>   File "/usr/src/homeassistant/homeassistant/config.py", line 329, in load_yaml_config_file
>     conf_dict = load_yaml(config_path)
>   File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 61, in load_yaml
>     with open(fname, encoding="utf-8") as conf_file:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/homeassistant/configuration.yaml'

The system works again if I delete this setting.

core-2021.1.5
Home Assistant OS 5.10
Raspberry Pi 4
